### ISSUE TITLE
Out of memory when running on FBMS?

### ISSUE THREAD

**Issue by adambielski** [YangtaoWANG95/TokenCut_video#2]
@YangtaoWANG95 I was trying to run the code on FBMS dataset, however the process gets killed likely due to exceeding the available memory (and I have 128GB). This line is the culprit: https://github.com/YangtaoWANG95/TokenCut_video/blob/master/graph.py#L62

Is the memory requirement really that high? Any way to circumvent it?

**Comment by YangtaoWANG95** [comment]
Hi adambielski,

I am sorry to reply you late. As you can imagine, if you want to build up the graph based on the entire graph, it requires a lot of memory. I run the code on a cluster with about 350 GB cpu memory. In you case, I would suggest you to reduce the 'max_frame' to a lower value: https://github.com/YangtaoWANG95/TokenCut_video/blob/d1f882ac3cb9444e981f9e87388782c96e4efe13/graph.py#L9.
The performance drops should not be that much.

Best,
Yangtao

**Comment by adambielski** [comment]
Thanks for your response @YangtaoWANG95 , I'll try reducing max_frame then.

**Comment by YangtaoWANG95** [comment]
It's my pleasure! 
P.S. I've read your paper MOVE, very interesting paper!

**Comment by adambielski** [comment]
Thanks man, I appreciate it! 😊
